import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../services/auth_service.dart';
import '../services/firestore_service.dart';
import '../models/user_model.dart';
import '../models/ride_model.dart';
import '../models/booking_model.dart';
import '../utils/fare_calculator.dart';

class BookingSummaryScreen extends StatefulWidget {
  final RideModel rideData;
  final ValueChanged<String> onConfirm;

  const BookingSummaryScreen({
    super.key,
    required this.rideData,
    required this.onConfirm,
  });

  @override
  State<BookingSummaryScreen> createState() => _BookingSummaryScreenState();
}

class _BookingSummaryScreenState extends State<BookingSummaryScreen> {
  bool _isLoading = false;
  UserModel? _driver;

  @override
  void initState() {
    super.initState();
    _fetchDriver();
  }

  Future<void> _fetchDriver() async {
    final driver = await AuthService.getUserProfile(widget.rideData.driverId);
    if (mounted) {
      setState(() => _driver = driver);
    }
  }

  Future<void> _handleConfirm() async {
    // Require login before booking
    if (!AuthService.isLoggedIn) {
      final didLogin = await AuthService.requireLogin(context);
      if (!didLogin || !mounted) return;
    }
    
    if (!AuthService.isLoggedIn) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Please login to book a ride')),
        );
      }
      return;
    }

    // Get the user ID (demo or real)
    final userId = AuthService.userId;

    // Prevent self-booking
    debugPrint('[BookingSummary] My userId: $userId, ride driverId: ${widget.rideData.driverId}');
    if (userId == widget.rideData.driverId) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('This is your ride ($userId vs ${widget.rideData.driverId})')),
        );
      }
      return;
    }

    setState(() => _isLoading = true);
    
    try {
      // Re-check seat availability in real-time before creating booking
      final latestRide = await FirestoreService().streamRide(widget.rideData.id).first;
      if (latestRide.seatsAvailable <= 0) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('This ride is now full. No seats available.',
                  style: GoogleFonts.inter(fontWeight: FontWeight.w600)),
              backgroundColor: const Color(0xFFEF4444),
              behavior: SnackBarBehavior.floating,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
            ),
          );
          setState(() => _isLoading = false);
        }
        return;
      }

      final booking = BookingModel(
        id: '', // Generated by Firestore
        rideId: widget.rideData.id,
        riderId: userId,
        status: BookingStatus.pending,
        otpVerified: false,
        createdAt: DateTime.now(),
      );
      
      final bookingId = await FirestoreService().createBooking(booking);
      
      if (mounted) {
        widget.onConfirm(bookingId);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to book: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    // Calculate fare using FareCalculator for accurate breakdown
    final distanceKm = FareCalculator.calculateDistance(
      widget.rideData.sourceLatLng.latitude,
      widget.rideData.sourceLatLng.longitude,
      widget.rideData.destinationLatLng.latitude,
      widget.rideData.destinationLatLng.longitude,
    );
    final fareInfo = FareCalculator.calculatePerPersonFare(distanceKm);
    
    double displayPrice = widget.rideData.pricePerSeat;
    double appFee = FareCalculator.appFeePerUser; // ₹2
    double sharedPrice = fareInfo.perPersonFare; // Actual per-person share before app fee
    double totalAutoFare = fareInfo.totalAutoFare;
    double soloSaving = fareInfo.savings;

    return Scaffold(
      backgroundColor: const Color(0xFFF5F7FA),
      body: SafeArea(
        child: Column(
          children: [
            // Header
            Padding(
              padding: const EdgeInsets.fromLTRB(24, 16, 24, 16),
              child: Row(
                children: [
                  GestureDetector(
                    onTap: () => Navigator.pop(context),
                    child: Container(
                      width: 42,
                      height: 42,
                      decoration: BoxDecoration(
                        color: Colors.white,
                        shape: BoxShape.circle,
                        boxShadow: [BoxShadow(color: Colors.black.withValues(alpha: 0.05), blurRadius: 8, offset: const Offset(0, 2))],
                      ),
                      child: const Icon(Icons.arrow_back, color: Color(0xFF1A1D26), size: 20),
                    ),
                  ),
                  Expanded(
                    child: Center(
                      child: Text(
                        'Booking Summary',
                        style: GoogleFonts.inter(fontSize: 18, fontWeight: FontWeight.w800, color: const Color(0xFF0F172A)),
                      ),
                    ),
                  ),
                  const SizedBox(width: 42),
                ],
              ),
            ),

            // Content
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 8),
                child: Column(
                  children: [
                    // Driver Card
                    _buildInfoCard(
                      child: Row(
                        children: [
                          CircleAvatar(
                            radius: 28, 
                            backgroundImage: _driver?.profilePhotoUrl != null ? NetworkImage(_driver!.profilePhotoUrl!) : null,
                            child: _driver?.profilePhotoUrl == null ? const Icon(Icons.person) : null,
                          ),
                          const SizedBox(width: 16),
                          Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('Host', style: GoogleFonts.inter(fontSize: 13, fontWeight: FontWeight.w600, color: const Color(0xFF64748B))),
                              const SizedBox(height: 2),
                              Text(_driver?.name ?? 'Loading...', style: GoogleFonts.inter(fontSize: 18, fontWeight: FontWeight.w800, color: const Color(0xFF0F172A))),
                            ],
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 16),

                    // Booking Details
                    _buildInfoCard(
                      child: Column(
                        children: [
                          Row(
                            children: [
                              Container(
                                width: 44, height: 44,
                                decoration: BoxDecoration(color: const Color(0xFFEFF6FF), borderRadius: BorderRadius.circular(12)),
                                child: const Icon(Icons.people_outline, color: Color(0xFF3B82F6), size: 20),
                              ),
                              const SizedBox(width: 16),
                              Expanded(child: Text('Seats', style: GoogleFonts.inter(fontSize: 15, fontWeight: FontWeight.w700, color: const Color(0xFF0F172A)))),
                              Text('1 Seat', style: GoogleFonts.inter(fontSize: 15, fontWeight: FontWeight.w800, color: const Color(0xFF0F172A))),
                            ],
                          ),
                          const Padding(
                            padding: EdgeInsets.symmetric(vertical: 12),
                            child: Divider(height: 1),
                          ),
                          Row(
                            children: [
                              Container(
                                width: 44, height: 44,
                                decoration: BoxDecoration(color: const Color(0xFFECFDF5), borderRadius: BorderRadius.circular(12)),
                                child: const Icon(Icons.receipt_long_outlined, color: Color(0xFF059669), size: 20),
                              ),
                              const SizedBox(width: 16),
                              Expanded(child: Text('Total Cost', style: GoogleFonts.inter(fontSize: 15, fontWeight: FontWeight.w700, color: const Color(0xFF0F172A)))),
                              Text('₹${displayPrice.toInt()}', style: GoogleFonts.inter(fontSize: 18, fontWeight: FontWeight.w800, color: const Color(0xFF059669))),
                            ],
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 16),

                    // Fare Breakdown
                    Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(24),
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(24),
                        border: Border.all(color: const Color(0xFFF1F5F9), width: 1.5),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text('Fare Breakdown', style: GoogleFonts.inter(fontSize: 16, fontWeight: FontWeight.w800, color: const Color(0xFF0F172A))),
                          const SizedBox(height: 20),
                          _buildBreakdownRow('Total Auto Fare', '₹${totalAutoFare.ceil()}'),
                          const SizedBox(height: 8),
                          _buildBreakdownRow('Split ÷ ${fareInfo.passengers}', '₹${sharedPrice.ceil()}'),
                          const SizedBox(height: 8),
                          _buildBreakdownRow('Platform Fee', '+ ₹${appFee.toInt()}'),
                          const Padding(
                            padding: EdgeInsets.symmetric(vertical: 12),
                            child: Divider(),
                          ),
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Text('You Pay', style: GoogleFonts.inter(fontSize: 15, fontWeight: FontWeight.w800, color: const Color(0xFF0F172A))),
                              Text('₹${displayPrice.ceil()}', style: GoogleFonts.inter(fontSize: 18, fontWeight: FontWeight.w800, color: const Color(0xFF2563EB))),
                            ],
                          ),
                          const SizedBox(height: 16),
                          Container(
                            padding: const EdgeInsets.all(12),
                            decoration: BoxDecoration(color: const Color(0xFFECFDF5), borderRadius: BorderRadius.circular(12)),
                            child: Row(
                              children: [
                                const Icon(Icons.savings_outlined, color: Color(0xFF059669), size: 18),
                                const SizedBox(width: 8),
                                Expanded(child: Text('You save ₹${soloSaving.ceil()} compared to a solo ride!', style: GoogleFonts.inter(fontSize: 12, fontWeight: FontWeight.w700, color: const Color(0xFF059669)))),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),

            // Bottom Confirm Button
            Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: Colors.white,
                boxShadow: [BoxShadow(color: Colors.black.withValues(alpha: 0.05), blurRadius: 20, offset: const Offset(0, -5))],
              ),
              child: SafeArea(
                top: false,
                child: SizedBox(
                  width: double.infinity,
                  height: 56,
                  child: ElevatedButton(
                    onPressed: _isLoading ? null : _handleConfirm,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: const Color(0xFF2563EB),
                      foregroundColor: Colors.white,
                      elevation: 0,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                    ),
                    child: _isLoading 
                      ? const SizedBox(width: 24, height: 24, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                      : Text('Confirm Joining', style: GoogleFonts.inter(fontSize: 16, fontWeight: FontWeight.w700)),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildBreakdownRow(String title, String value) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(title, style: GoogleFonts.inter(fontSize: 14, fontWeight: FontWeight.w500, color: const Color(0xFF64748B))),
        Text(value, style: GoogleFonts.inter(fontSize: 14, fontWeight: FontWeight.w700, color: const Color(0xFF0F172A))),
      ],
    );
  }

  Widget _buildInfoCard({required Widget child}) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [BoxShadow(color: Colors.black.withValues(alpha: 0.02), blurRadius: 10, offset: const Offset(0, 4))],
      ),
      child: child,
    );
  }
}
